import type { ComplimentEntry } from '../types/content';

/**
 * Short compliment lines for the infinite compliment daisy Easter egg
 * (see ComplimentDaisy.tsx). Mix of sincere, romantic, funny, playful,
 * and slightly ridiculous — keep each one short, one sentence,
 * mobile-readable. Safe to edit or add more freely.
 */
export const compliments: ComplimentEntry[] = [
  { id: 'compliment-1', text: 'Your laugh is my favorite soundtrack.' },
  { id: 'compliment-2', text: 'You have excellent taste. and you taste excellent. yup, i said it.' },
  { id: 'compliment-3', text: 'You somehow make ordinary days feel special.' },
  { id: 'compliment-4', text: "You're ridiculously cute." },
  { id: 'compliment-5', text: "You're my favorite notification." },
  { id: 'compliment-6', text: 'The world is objectively better with you in it.' },
  { id: 'compliment-7', text: 'You are so pretty, its out of this world.' },
  { id: 'compliment-8', text: 'Your brain is one of my favorite places.' },
  { id: 'compliment-9', text: "You're the human version of a warm blanket." },
  { id: 'compliment-10', text: 'I would 100% trade my last fry for you.' },
  { id: 'compliment-11', text: 'You make my life so much easier.' },
  { id: 'compliment-12', text: 'Your voice is a top-tier comfort sound.' },
  { id: 'compliment-13', text: "You're annoyingly good at making me smile." },
  { id: 'compliment-14', text: 'You are so perfectly, completely, breathtakingly beautiful.' },
  { id: 'compliment-15', text: "I'd pick you again in every version of this." },
  { id: 'compliment-16', text: 'I love you in all universes.' },
  { id: 'compliment-17', text: "You're the best plot twist I've had." },
  { id: 'compliment-18', text: 'You make me feel really safe.' },
  { id: 'compliment-19', text: 'Your silly little jokes are elite tier.' },
  { id: 'compliment-20', text: "You're kind in the quiet ways too, not just loud ones." },
  { id: 'compliment-21', text: 'You make me want to be a better, softer person.' },
  { id: 'compliment-22', text: "You have made my heart so much softer." },
  { id: 'compliment-23', text: 'You have a beautiful soul.' },
  { id: 'compliment-24', text: 'You are, factually, adorable.' },
  { id: 'compliment-25', text: "I like the way you exist. That's it. That's the compliment." },
  { id: 'compliment-26', text: 'You could make a grocery list sound charming.' },
  { id: 'compliment-27', text: "You're the reason my phone battery dies so fast." },
  { id: 'compliment-28', text: 'yu are unreasonably gorgeous.' },
  { id: 'compliment-29', text: "You're stuck with me now, sorry :))" },
  { id: 'compliment-30', text: 'You are, in every measurable way, my favorite person.' },
  { id: 'compliment-31', text: 'You make quiet moments feel like enough.' },
  { id: 'compliment-32', text: "You're proof that good things do happen to me." },
  { id: 'compliment-33', text: "You have a face that makes me feel like home." },
  { id: 'compliment-34', text: "Looking at your beautiful face is the most peaceful thing i have ever done." },
  { id: 'compliment-35', text: "You are my STAR." },
  { id: 'compliment-36', text: "You make me the proudest." },
  { id: 'compliment-37', text: "Your smile melts my heart like an ice cream cone at the beach." },
  { id: 'compliment-38', text: "You are absolutely perfect and perfectly complete." },
  { id: 'compliment-39', text: "You are a really good person." },
  { id: 'compliment-40', text: "Your eyes are so deep like the ocean, so pretty like stars." },
  { id: 'compliment-41', text: "You are such a pure soul." },
  { id: 'compliment-42', text: "Are you an angel? cause uhhh.... you look like one." },
  { id: 'compliment-43', text: "And i keep falling for you, and falling, and falling, and fallng, and falling, and falling, and falling..." },
  { id: 'compliment-44', text: "You have the softest heart in all the people i know." },
  { id: 'compliment-45', text: "Your voice is really cute hehe." },
  { id: 'compliment-46', text: "I want to gaze at your beautiful face for my whol life, without breaks." },
  { id: 'compliment-47', text: "It feels like every problem goes away when you laugh." },
  { id: 'compliment-48', text: "loving you is my job now, and i would take no vacation days, would work weekends and overtime." },
  { id: 'compliment-49', text: "Are you Wifi? cause i keep staring at you like a stupid. yeah that doesnt make sense, but its true." },
  { id: 'compliment-50', text: "Okay so i was gonna use a pickup line, but when you come to mind, my brain just goes blank." },
  { id: 'compliment-51', text: "[PICKUP LINE] (please be mine)" },
  { id: 'compliment-52', text: "Helluuu (with the intent of rizzing you up)." },
  { id: 'compliment-53', text: "You are so unfairly, unfathomably attractive." },
  { id: 'compliment-54', text: "I don't believe in love at first sight, but i do believe in love at every sight. Has been happening everytime i see you." },
  { id: 'compliment-55', text: "Your hair is so magnificent." },
  { id: 'compliment-56', text: "You're so cute i want to eat you. and then i wnat to eat you out. hehe." },
  { id: 'compliment-57', text: "Who knew that a silly sweet gurl with glasses, beautiful eyes, short height and such a beautiful smile would make me go crazy. And so happy." },
  { id: 'compliment-58', text: "You are so hot the sun is scared of you. for real tho, You are very hot." },
  { id: 'compliment-59', text: "Are you an accountant cause i need to be taxed. By you. Please." },
  { id: 'compliment-60', text: "You are very beautiful issu." },
];